- hosts: servers
  become: yes
  collections:
    - community.docker

  vars:
    users:
      - username: shoeb
        password: "shoeb123"
        email: syedshoeb8380@gmail.com
      - username: abrar
        password: "abrar123"
        email: syedabrar7757@gmail.com
    notebook_dir: /opt/notebooks

  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create users with hashed passwords
      user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        shell: /bin/bash
        state: present
        create_home: yes
      loop: "{{ users }}"

    - name: Add users to docker group
      user:
        name: "{{ item.username }}"
        groups: docker
        append: yes
      loop: "{{ users }}"

    - name: Pull PySpark notebook Docker image
      docker_image:
        name: jupyter/pyspark-notebook:latest
        source: pull

    - name: Ensure notebook directory exists on host
      file:
        path: "{{ notebook_dir }}"
        state: directory
        mode: '0777'

    - name: Create a PySpark Sample Jupyter Notebook file
      copy:
        dest: "{{ notebook_dir }}/PySparkSample.ipynb"
        content: |
          {
           "cells": [
            {
             "cell_type": "code",
             "execution_count": null,
             "metadata": {},
             "outputs": [],
             "source": [
               # (your notebook JSON content here)
             ]
            }
           ],
           "metadata": {
             "kernelspec": {
               "display_name": "Python 3",
               "language": "python",
               "name": "python3"
             },
             "language_info": {
               "name": "python",
               "version": "3.9.12"
             }
           },
           "nbformat": 4,
           "nbformat_minor": 4
          }

    - name: Run PySpark Jupyter notebook container
      docker_container:
        name: pyspark-notebook-container
        image: jupyter/pyspark-notebook:latest
        state: started
        restart_policy: always
        ports:
          - "9870:8888"
        volumes:
          - "{{ notebook_dir }}:/home/jovyan/work"
        command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
