- hosts: servers
  become: yes

  vars:
    users:
      - username: shoeb
        password: shoeb123
        email: syedshoeb8380@gmail.com
      - username: abrar
        password: abrar123
        email: syedabrar7757@gmail.com

  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create users with plain text passwords
      user:
        name: "{{ item.username }}"
        password: "{{ item.password | password_hash('sha512', 'mysecretsalt') }}"
        shell: /bin/bash
        state: present
        create_home: yes
      loop: "{{ users }}"

    - name: Add users to docker group
      loop: "{{ users }}"
      vars:
        user_data: "{{ item }}"
      user:
        name: "{{ user_data.username }}"
        groups: docker
        append: yes

    - name: Send email with credentials
      loop: "{{ users }}"
      vars:
        user_data: "{{ item }}"
      mail:
        subject: "Your Account on {{ inventory_hostname }}"
        to: "{{ user_data.email }}"
        body: |
          Hello {{ user_data.username }},

          Your account has been created on {{ inventory_hostname }}.
          Username: {{ user_data.username }}
          Password: {{ user_data.password }}

          Thanks,
          Admin
        from: "shoeb.corporate@gmail.com"
        host: smtp.gmail.com
        port: 587
        username: "{{ lookup('env', 'SMTP_USER') }}"
        password: "{{ lookup('env', 'SMTP_PASS') }}"
        secure: starttls
