- hosts: servers
  become: yes

  vars:
    # This will hold processed user lines like ["user1,password1,email1", ...]
    users: []

  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure apt cache is updated
      apt:
        update_cache: yes

    # 🔽 USER HANDLING STARTS HERE 🔽

    - name: Read users from CSV file
      slurp:
        src: users.csv
      register: user_csv

    - name: Parse users from CSV
      set_fact:
        users: "{{ user_csv.content | b64decode | splitlines }}"

    - name: Create users
      loop: "{{ users }}"
      vars:
        user_data: "{{ item.split(',') }}"
      user:
        name: "{{ user_data[0] }}"
        password: "{{ user_data[1] | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes

    - name: Add users to docker group
      loop: "{{ users }}"
      vars:
        user_data: "{{ item.split(',') }}"
      user:
        name: "{{ user_data[0] }}"
        groups: docker
        append: yes

    - name: Send email with credentials
      loop: "{{ users }}"
      vars:
        user_data: "{{ item.split(',') }}"
      mail:
        subject: "Your Account on {{ inventory_hostname }}"
        to: "{{ user_data[2] }}"
        body: |
          Hello {{ user_data[0] }},

          Your account has been created on {{ inventory_hostname }}.
          Username: {{ user_data[0] }}
          Password: {{ user_data[1] }}

          Thanks,
          Admin
        from: "shoeb.corporate@gmail.com"
        smtp_host: smtp.gmail.com
        smtp_port: 587
        smtp_user: "{{ lookup('env', 'SMTP_USER') }}"
        smtp_password: "{{ lookup('env', 'SMTP_PASS') }}"
