- hosts: servers
  become: yes

  vars:
    users:
      - { username: "shoeb", password: "shoeb123", email: "syedshoeb8380@gmail.com" }
      - { username: "abrar", password: "abrar123", email: "syedabrar7757@gmail.com" }

  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create users with hashed passwords
      loop: "{{ users }}"
      loop_control:
        label: "{{ item.username }}"
      user:
        name: "{{ item.username }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes

    - name: Add users to docker group
      loop: "{{ users }}"
      user:
        name: "{{ item.username }}"
        groups: docker
        append: yes

    - name: Send email with credentials
      loop: "{{ users }}"
      mail:
        subject: "Your Account on {{ inventory_hostname }}"
        to: "{{ item.email }}"
        body: |
          Hello {{ item.username }},

          Your account has been created on {{ inventory_hostname }}.
          Username: {{ item.username }}
          Password: {{ item.password }}

          Thanks,
          Admin
        from: "shoeb.corporate@gmail.com"
        smtp_host: smtp.gmail.com
        smtp_port: 587
        smtp_user: "{{ lookup('env', 'SMTP_USER') }}"
        smtp_password: "{{ lookup('env', 'SMTP_PASS') }}"
