- hosts: servers
  become: yes
  vars:
    users: "{{ lookup('file', 'users.csv').splitlines() }}"

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes
        
    - name: Ensure Python 3 and pip are installed
      apt:
        name:
          - python3
          - python3-pip
        update_cache: yes
        state: present

    - name: Install passlib
      pip:
        name: passlib
        executable: pip3
        
    - name: Install passlib using the Python interpreter Ansible uses
      ansible.builtin.pip:
        name: passlib
        executable: "{{ ansible_python.executable }}"


    - name: Create users
      loop: "{{ users }}"
      vars:
        user_data: "{{ item.split(',') }}"
      user:
        name: "{{ user_data[0] }}"
        password: "{{ user_data[1] | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes

    - name: Add user to docker group
      loop: "{{ users }}"
      vars:
        username: "{{ item.split(',')[0] }}"
      user:
        name: "{{ username }}"
        groups: docker
        append: yes

    - name: Send email with credentials
      loop: "{{ users }}"
      vars:
        u: "{{ item.split(',') }}"
      mail:
        subject: "Your Account on {{ inventory_hostname }}"
        to: "{{ u[2] }}"
        body: |
          Hello {{ u[0] }},
          
          Your account has been created on {{ inventory_hostname }}.
          Username: {{ u[0] }}
          Password: {{ u[1] }}

          Thanks,
          Admin
        from: "shoeb.corporate@gmail.com"
        smtp_host: smtp.gmail.com
        smtp_port: 587
        smtp_user: "{{ lookup('env', 'SMTP_USER') }}"
        smtp_password: "{{ lookup('env', 'SMTP_PASS') }}"
