- hosts: servers
  become: yes

  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy hashed-users.csv to VM
      copy:
        src: hashed-users.csv
        dest: /tmp/hashed-users.csv

    - name: Read users from CSV file
      community.general.read_csv:
        path: /tmp/hashed-users.csv
      register: users_csv

    - name: Set user lines
      set_fact:
        user_lines: "{{ users_csv.list }}"

    - name: Create users
      loop: "{{ user_lines }}"
      vars:
        user_data: "{{ item }}"
      user:
        name: "{{ user_data.username }}"
        password: "{{ user_data.password }}"
        shell: /bin/bash
        create_home: yes

    - name: Add users to docker group
      loop: "{{ user_lines }}"
      vars:
        user_data: "{{ item }}"
      user:
        name: "{{ user_data.username }}"
        groups: docker
        append: yes

    - name: Send email with credentials
      loop: "{{ user_lines }}"
      vars:
        user_data: "{{ item }}"
      mail:
        subject: "Your Account on {{ inventory_hostname }}"
        to: "{{ user_data.email }}"
        body: |
          Hello {{ user_data.username }},

          Your account has been created on {{ inventory_hostname }}.
          Username: {{ user_data.username }}
          Password: {{ user_data.password }}

          Thanks,
          Admin
        from: "shoeb.corporate@gmail.com"
        smtp_host: smtp.gmail.com
        smtp_port: 587
        smtp_user: "{{ lookup('env', 'SMTP_USER') }}"
        smtp_password: "{{ lookup('env', 'SMTP_PASS') }}"
