- hosts: servers
  become: yes

  vars:
    users:
      - "shoeb,Pass@123,syedshoeb8380@gmail.com"
      - "abrar,Pass@123,syedabrar7757@gmail.com"

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create users
      loop: "{{ users }}"
      vars:
        user_data: "{{ item.split(',') }}"
      user:
        name: "{{ user_data[0] }}"
        password: "{{ user_data[1] | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes

    - name: Add users to docker group
      loop: "{{ users }}"
      vars:
        username: "{{ item.split(',')[0] }}"
      user:
        name: "{{ username }}"
        groups: docker
        append: yes

    - name: Send email with user credentials
      loop: "{{ users }}"
      vars:
        user_data: "{{ item.split(',') }}"
        username: "{{ user_data[0] }}"
        password: "{{ user_data[1] }}"
        email: "{{ user_data[2] }}"
      mail:
        subject: "Your New Linux Account"
        to: "{{ email }}"
        body: |
          Hello {{ username }},

          Your account has been created on {{ inventory_hostname }}.
          You can SSH into the server using:

          Username: {{ username }}
          Password: {{ password }}

          Regards,
          Admin
