name: 'Terraform CI on GCP'

on:
  workflow_dispatch:

jobs:
  terraform-ansible:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4

      - name: Create GCP credentials file
        run: echo "${GOOGLE_CREDENTIALS}" > service-account.json

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          echo "${SSH_PUBLIC_KEY}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="gcp_credentials_file=service-account.json" -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="gcp_credentials_file=service-account.json"

      - name: Get Public IP of Instance
        id: ip
        run: |
          IP=$(terraform output -raw instance_public_ip)
          echo "instance_ip=$IP" >> $GITHUB_ENV
          echo "Instance IP: $IP"

      - name: Create Ansible Inventory File
        run: |
          echo "[servers]" > ../ansible/inventory.ini
          echo "${{ env.instance_ip }} ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ../ansible/inventory.ini

      - name: Run Ansible Playbook
        working-directory: ./ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible-playbook -i inventory.ini playbook.yml
