name: 'Terraform + Ansible on GCP'

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4

      - name: Create credentials file
        run: echo "${GOOGLE_CREDENTIALS}" > service-account.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          echo "${SSH_PUBLIC_KEY}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -out=tfplan \
            -var="gcp_credentials_file=service-account.json" \
            -var="region=us-central1" \
            -var="zone=us-central1-a" \
            -var="ssh_public_key=~/.ssh/id_rsa.pub"
        continue-on-error: true

      - name: Check Plan Result
        id: plan-check
        run: |
          if terraform show -json tfplan | jq -e '.resource_changes | length == 0'; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Apply
        if: steps.plan-check.outputs.no_changes == 'false'
        run: terraform apply -auto-approve tfplan

      - name: Run Ansible Playbook
        run: |
          sudo apt update && sudo apt install -y ansible
          ansible-playbook -i inventory.ini playbook.yml
        working-directory: ./ansible

