name: Ansible Provisioning

on:
  push:
    branches:
      - main

jobs:
  provision:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: your-gcp-project-id
      ZONE: your-vm-zone
      INSTANCE_NAME: your-instance-name
      PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Fetch external IP of GCP instance
        id: get-ip
        run: |
          IP=$(gcloud compute instances describe "$INSTANCE_NAME" \
            --zone="$ZONE" \
            --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
          echo "PUBLIC_IP=$IP" >> $GITHUB_ENV

      - name: Write private key to file
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 600 key.pem

      - name: Generate dynamic Ansible inventory
        run: |
          echo "[servers]" > ansible/inventory.ini
          echo "$PUBLIC_IP ansible_user=ubuntu ansible_ssh_private_key_file=key.pem" >> ansible/inventory.ini

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible playbook
        run: |
          ansible-playbook ansible/playbook.yml -i ansible/inventory.ini
