name: Terraform + Ansible Provisioning

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    outputs:
      instance_ip: ${{ steps.get_ip.outputs.instance_ip }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Set up GCP credentials
      run: |
        echo "${{ secrets.GCP_CREDENTIALS }}" > gcp-creds.json
      shell: bash

    - name: Terraform Init & Apply
      run: |
        terraform init
        terraform apply -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    - name: Get Instance IP
      id: get_ip
      run: |
        IP=$(terraform output -raw instance_ip)
        echo "instance_ip=$IP" >> $GITHUB_OUTPUT

  ansible:
    name: Run Ansible Playbook
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
        echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n" > ~/.ssh/config

    - name: Add Host to Known Hosts
      run: |
        ssh-keyscan -H ${{ needs.terraform.outputs.instance_ip }} >> ~/.ssh/known_hosts

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Create Ansible Inventory
      run: |
        echo "[servers]" > inventory.ini
        echo "${{ needs.terraform.outputs.instance_ip }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> inventory.ini

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory.ini playbook.yml
