name: Run Ansible Only

on:
  workflow_dispatch:

jobs:
  ansible:
    name: Run Ansible on Existing VM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
        echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n" > ~/.ssh/config
        
    - name: Prepare Ansible Inventory
      run: |
        echo "[servers]" > ./ansible/inventory.ini
        echo "$INSTANCE_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ./ansible/inventory.ini
      
    - name: Install Ansible
      run: |
        sudo apt update && sudo apt install -y ansible

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory.ini playbook.yml
      working-directory: ./ansible
